version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    open-pull-requests-limit: 0

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    open-pull-requests-limit: 0