# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.response_page_metadata import ResponsePageMetadata  # noqa: E501
from openapi_server.models.response_page_metadata_links import ResponsePageMetadataLinks  # noqa: E501
from openapi_server.models.tool import Tool  # noqa: E501
from openapi_server import util


class PageOfTools(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, offset=None, limit=None, links=None, tools=None):  # noqa: E501
        """PageOfTools - a model defined in OpenAPI

        :param offset: The offset of this PageOfTools.  # noqa: E501
        :type offset: int
        :param limit: The limit of this PageOfTools.  # noqa: E501
        :type limit: int
        :param links: The links of this PageOfTools.  # noqa: E501
        :type links: ResponsePageMetadataLinks
        :param tools: The tools of this PageOfTools.  # noqa: E501
        :type tools: List[Tool]
        """
        self.openapi_types = {
            'offset': int,
            'limit': int,
            'links': ResponsePageMetadataLinks,
            'tools': List[Tool]
        }

        self.attribute_map = {
            'offset': 'offset',
            'limit': 'limit',
            'links': 'links',
            'tools': 'tools'
        }

        self._offset = offset
        self._limit = limit
        self._links = links
        self._tools = tools

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfTools':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfTools of this PageOfTools.  # noqa: E501
        :rtype: PageOfTools
        """
        return util.deserialize_model(dikt, cls)

    @property
    def offset(self):
        """Gets the offset of this PageOfTools.

        Index of the first result that must be returned  # noqa: E501

        :return: The offset of this PageOfTools.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this PageOfTools.

        Index of the first result that must be returned  # noqa: E501

        :param offset: The offset of this PageOfTools.
        :type offset: int
        """
        if offset is None:
            raise ValueError("Invalid value for `offset`, must not be `None`")  # noqa: E501

        self._offset = offset

    @property
    def limit(self):
        """Gets the limit of this PageOfTools.

        Maximum number of results returned  # noqa: E501

        :return: The limit of this PageOfTools.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this PageOfTools.

        Maximum number of results returned  # noqa: E501

        :param limit: The limit of this PageOfTools.
        :type limit: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    @property
    def links(self):
        """Gets the links of this PageOfTools.


        :return: The links of this PageOfTools.
        :rtype: ResponsePageMetadataLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this PageOfTools.


        :param links: The links of this PageOfTools.
        :type links: ResponsePageMetadataLinks
        """
        if links is None:
            raise ValueError("Invalid value for `links`, must not be `None`")  # noqa: E501

        self._links = links

    @property
    def tools(self):
        """Gets the tools of this PageOfTools.

        An array of Tools  # noqa: E501

        :return: The tools of this PageOfTools.
        :rtype: List[Tool]
        """
        return self._tools

    @tools.setter
    def tools(self, tools):
        """Sets the tools of this PageOfTools.

        An array of Tools  # noqa: E501

        :param tools: The tools of this PageOfTools.
        :type tools: List[Tool]
        """

        self._tools = tools
